services:
  ujc_repo:
    build: .
    ports:
      - '4001:4002'
    environment:
      DATABASE_URL: postgresql://postgres:adminsecret@postgres:5432/ujc_repo_db
      DATABASE_USER: postgres
      DATABASE_PASS: adminsecret
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: ujc_repo_db
      NODE_ENV: production
      JWT_ISSUER: UJCRepo
      SECRET_KEY: 37e9d6ab3e33d16a4f521d0421feeb29be71479cf2cb80e97b62f0bde71c7d3a
      PORT: 4002
    volumes:
      - uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4001/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16.0
    container_name: ujc_repo_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-trust}
    networks:
      - ujcreponet
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  ujcreponet:
    driver: bridge